### ISSUE TITLE
Generic checklist #1

### ISSUE THREAD

**Issue by AbsurdlySuspicious** [AbsurdlySuspicious/ametro#15]
Some features I've already started or done implementing without creating an issue

- [x] General maintenance (update gradle, deps and sdk, use androidx, etc)
  - `minSdkVersion` is kept at 15 (Android 4.0.4) and I will try to keep it like that as long as possible
- [x] Update route start/end selection panel (fc3e3c79b088eee899736a014a04faab0f02d8e9)
- [x] Fix laggy map rendering / dedicate rendering to non-ui thread (b84087d5cc04eef6173775a41ae3b1c9466c2f1d and more)
